import { StyleSheet } from "react-native";

export const homePageStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF",
    paddingHorizontal: 15,
    paddingVertical: 20,
  },
  header: {
    marginTop: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  userInfo: {
    marginBottom: 20,
    alignItems: "center",
  },
  greeting: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FF6F00",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 16,
    color: "#666666",
    textAlign: "center",
    marginTop: 5,
  },
  cardsContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 20,
  },
  card: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    paddingVertical: 20,
    marginHorizontal: 8,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#FF6F00",
    alignItems: "center",
    justifyContent: "center",
  },
  cardFull: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    paddingVertical: 25,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#FF6F00",
    alignItems: "center",
    justifyContent: "center",
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FF6F00",
    textAlign: "center",
  },
  navBar: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "#FFF",
    paddingVertical: 15,
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
    elevation: 2,
  },
  navItem: {
    alignItems: "center",
  },
  navText: {
    fontSize: 14,
    color: "#666666",
    fontWeight: "bold",
  },
  navTextActive: {
    fontSize: 14,
    color: "#FF6F00",
    fontWeight: "bold",
  },
  kidModeTitle: {
    fontSize: 28, 
    fontWeight: "bold",
    color: "#ff4757", 
    textAlign: "center",
    textShadowColor: "#ffcc00", 
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
  },
});
