import { StyleSheet } from "react-native";

export const welcomeScreenStyles = StyleSheet.create({
  container: {
    flexGrow: 1,             // so ScrollView centers properly
    backgroundColor: "#F5F5F5",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  animatedText: {
    fontSize: 36,
    lineHeight: 32,
    color: "#2C3E50",
    textAlign: "center",
    marginBottom: 30,
    fontFamily: "Georgia",
    fontStyle: "italic",
  },
  card: {
    width: "100%",
    maxWidth: 400,           // limit width on larger screens
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 5,
  },
  title: {
    fontSize: 30,
    fontFamily: "Georgia",
    fontWeight: "700",
    color: "#2C3E50",
    marginBottom: 10,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 16,
    fontFamily: "Georgia",
    color: "#34495E",
    marginBottom: 20,
    textAlign: "center",
  },
  input: {
    width: "100%",
    backgroundColor: "#fff",
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 30,
    fontSize: 16,
    color: "#333",
    marginBottom: 15,
    fontFamily: "Georgia",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    textAlign: "left",
  },
  errorText: {
    color: "red",
    fontFamily: "Georgia",
    marginBottom: 10,
    textAlign: "center",
  },
  button: {
    backgroundColor: "#fff",
    width: "100%",
    paddingVertical: 15,
    borderRadius: 30,
    alignItems: "center",
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonText: {
    color: "#EFA550",
    fontFamily: "Georgia",
    fontSize: 18,
    fontWeight: "600",
  },
  signUpButton: {
    backgroundColor: "#2C3E50",
    width: "100%",
    paddingVertical: 15,
    borderRadius: 30,
    alignItems: "center",
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  signUpButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    fontFamily: "Georgia",
  },
  forgotPassword: {
    marginTop: 5,
  },
  forgotPasswordText: {
    color: "#444",
    fontFamily: "Georgia",
    fontSize: 16,
    textDecorationLine: "underline",
    textAlign: 'center',
  },
});
