import { StyleSheet } from 'react-native';

export const welcomeScreenStyles = StyleSheet.create({
  welcomeContainer: {
    flex: 1,
    backgroundColor: '#EAF6FF', // Light blue background
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  welcomeTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#005A9C', 
    position: 'absolute',
    top: 60,
    paddingTop: 40,
  },
  welcomeInput: {
    width: '90%',
    height: 50,
    borderWidth: 1,
    borderColor: '#B0C4DE',
    borderRadius: 8,
    paddingHorizontal: 15,
    marginBottom: 10,
    backgroundColor: '#fff',
    color: '#333',
    fontSize: 16,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3, // Android shadow
  },
  welcomeForgotPassword: {
    alignSelf: 'flex-end',
    color: '#007ACC',
    fontSize: 14,
    marginTop: -10,
    marginBottom: 20,
    textDecorationLine: 'underline',
  },
  welcomeLoginButton: {
    backgroundColor: '#007ACC',
    paddingVertical: 14,
    width: '50%',
    borderRadius: 8,
    marginBottom: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  welcomeButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  welcomeSignUpButton: {
    paddingVertical: 14,
    width: '50%',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#007ACC',
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  welcomeSignUpText: {
    color: '#007ACC',
    fontSize: 18,
    fontWeight: '600',
  },
  indexTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#555',
    textAlign: 'center',
    marginBottom: 30,
    paddingHorizontal: 10,
  },
  indexSubtitle: {
    fontSize: 14,
    color: '#555',
    textAlign: 'center',
    marginTop: 20,
    paddingHorizontal: 30,
  },
});
